const sampleListing = [
  {
    title: "Cozy Mountain Cabin",
    description: "A peaceful retreat in the mountains.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    price: 120,
    location: "Manali, Himachal Pradesh",
    country: "India",
  },
  {
    title: "Urban Loft",
    description: "Modern loft in the heart of downtown.",
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb",
    price: 200,
    location: "New York City, NY",
    country: "USA",
  },
  {
    title: "Beachside Bungalow",
    description: "A beautiful stay near the beach.",
    image: "https://images.unsplash.com/photo-1505691723518-36a5ac3e37b4",
    price: 180,
    location: "Goa",
    country: "India",
  },
  {
    title: "Desert Oasis",
    description: "A luxury resort in the desert.",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    price: 300,
    location: "Jaisalmer, Rajasthan",
    country: "India",
  },
  {
    title: "Forest Treehouse",
    description: "Experience nature in a cozy treehouse.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    price: 140,
    location: "Coorg",
    country: "India",
  },
  {
    title: "Lakeside Villa",
    description: "Stunning views from a peaceful lakeside home.",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae",
    price: 250,
    location: "Nainital",
    country: "India",
  },
  {
    title: "Rustic Farmhouse",
    description: "A countryside stay with a vintage feel.",
    image: "https://images.unsplash.com/photo-1523217582562-09d0def993a6",
    price: 160,
    location: "Punjab",
    country: "India",
  },
  {
    title: "Modern Apartment",
    description: "Fully furnished city apartment.",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
    price: 190,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Island Cottage",
    description: "Private cottage on a tropical island.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 275,
    location: "Andaman Islands",
    country: "India",
  },
  {
    title: "Hilltop Cabin",
    description: "Panoramic views from a cozy cabin.",
    image: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb",
    price: 150,
    location: "Shimla",
    country: "India",
  },
  {
    title: "Vintage Studio",
    description: "Old-school charm in a modern city.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 110,
    location: "Pune",
    country: "India",
  },
  {
    title: "Mountain View Hotel",
    description: "Comfort with a view of the peaks.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 200,
    location: "Leh",
    country: "India",
  },
  {
    title: "Riverside Home",
    description: "Peaceful stay by the river.",
    image: "https://images.unsplash.com/photo-1572120360610-d971b9b78825",
    price: 130,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Luxury Penthouse",
    description: "Top-floor luxury with skyline views.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    price: 500,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Desert Camp",
    description: "Camping under the stars in the desert.",
    image: "https://images.unsplash.com/photo-1618773928121-2f1e50d2c9e5",
    price: 100,
    location: "Thar Desert",
    country: "India",
  },
  {
    title: "Cultural Homestay",
    description: "Live like a local with a host family.",
    image: "https://images.unsplash.com/photo-1557804506-669a67965ba0",
    price: 80,
    location: "Varanasi",
    country: "India",
  },
  {
    title: "Romantic Cottage",
    description: "Perfect for couples seeking quiet time.",
    image: "https://images.unsplash.com/photo-1578898886096-9f7e74a0ef81",
    price: 210,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Jungle Resort",
    description: "Luxury stay in the middle of a jungle.",
    image: "https://images.unsplash.com/photo-1590490350420-e6b8a2873c8a",
    price: 290,
    location: "Jim Corbett",
    country: "India",
  },
  {
    title: "Colonial House",
    description: "Experience colonial architecture and comfort.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    price: 170,
    location: "Chennai",
    country: "India",
  },
  {
    title: "Skyline Flat",
    description: "Bright, modern flat with skyline view.",
    image: "https://images.unsplash.com/photo-1600585154204-155eac934f2b",
    price: 220,
    location: "Hyderabad",
    country: "India",
  },
];

module.exports = { data: sampleListing };
